@startuml Usecase
left to right direction
skinparam packageStyle rectangle

actor "Администратор" as admin
actor "Клиент" as client

rectangle "Система" {
    ' Прецеденты для Администратора
    usecase "Регистрация" as reg_admin
    usecase "Вход в систему" as login_admin
    usecase "База клиентов" as db_clients
    usecase "База тренеров" as db_trainers
    usecase "Просмотр\nрасписания" as view_schedule_admin
    
    usecase "Регистрация клиентов\n(оформление\nабонементов)" as reg_clients
    usecase "Регистрация тренеров" as reg_trainers
    usecase "Изменение\nрасписания" as edit_schedule
    
    ' Прецеденты для Клиента
    usecase "Регистрация" as reg_client
    usecase "Вход в систему" as login_client
    usecase "Просмотр\nрасписания" as view_schedule_client
    usecase "Запись на занятие" as book_lesson
    usecase "Проверка\nсвободных мест" as check_places
}

' Связи для Администратора
admin - reg_admin
reg_admin - login_admin
login_admin - db_clients
login_admin - db_trainers
login_admin - view_schedule_admin

db_clients - reg_clients
db_trainers - reg_trainers
view_schedule_admin - edit_schedule

' Связи для Клиента
client - reg_client
reg_client - login_client
login_client - view_schedule_client
login_client - book_lesson

book_lesson .> check_places : <<Include>>

@enduml
